### ISSUE TITLE
Week 7 Project Assignment Feedback

### ISSUE THREAD

**Issue by emily1129** [cryptodelta2023/Giftlist#13]
1. A reminder for you to update your comment, for example, there is no `new document` related object in your file.
https://github.com/cryptodelta2023/Giftlist/blob/632efb247798100c95e52f506e80e619cdc12bb1/app/models/list_doc.rb#L12

**Comment by Anita77128230** [comment]
Okay! We'll check all comments more carefully before pushing onto github.
